<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<style type="text/css">
	.title{
		font-weight: 700;
	}
	img {
  border: 1px solid #ddd;
  border-radius: 4px;
  padding: 5px;
  margin-top: 5px;
  width: 150px;
}
#menu li{
	display: inline;
}
table#ledgend  th, td {
	 border: 1px solid black;
}
</style>
<body>
	<div align="center">
		<h2>{{ $project_name }}
			<p>Periodic Report</p> 
		</h2>
	</div>
	<h3>
		<p>
			Date: {{ date('d M Y', strtotime($start_date)) }} to {{ date('d M Y', strtotime($end_date)) }}
		</p>
	</h3>

<section>
<ol>
	<?php  
         $i= 0;
         $completed = 0;
         $ongoing = 0;
         $schedule = 0;

	 ?>
	@foreach($data as $dat)
	
  <li><span class="title">{{$dat->first()[0]->category->name}} (Total Work:{{$count_task[$i++]}})</span>

  	    <ol style="list-style-type: square;">
  	    	@foreach($dat as $d)
		    
		    	<li><span class="title">{{$d[0]->tasksubcat->name}} ({{count($d)}})</span></li>
		    	<ol style="list-style-type: circle;">
		    	@foreach($d as $key=>$mr)
		      <li><span>{{$mr->subject}}</span>
		      <br><span style="font-size: x-small;">
		      	@if( $mr->schedule == 'on' )
		      		Schedule: <mark>{{ucfirst($mr->schedule_type)}}</mark>
		      	@else


		      	Status:
		      	@if($mr->status == 'ongoing') 
		       <mark style='background: red;color: white;'>{{  ucfirst($mr->status) }}</mark>
		       @else
		       	 <mark style='background: green;color: white;'>{{  ucfirst($mr->status) }}</mark>
		       @endif
		      </span>

		      	@endif 
		      <?php 
		      	if($mr->schedule == 'on')
		      		$schedule++;
		      	elseif($mr->status == 'completed')
		      		$completed++;
		      	elseif($mr->status == 'ongoing')
		      		$ongoing++;
		      ?> 	
				<dl>
					@if($mr->description)
						<dd>{!! $mr->description !!}</dd>
					@endif
					@if($mr->attachment)
					<dt>Attachment </dt>
					<dd>
						<a target="_blank" href="img_forest.jpg">
							<img src="{{ public_path().'/task_attachments/'.$mr->attachment }}" alt="{{ $mr->subject }}" style="width:150px">
						</a>
					</dd>
					@endif
				</dl>
						@if(count($mr->projectTaskAttachent) > 0 )
					<br><br>
					<ul id="menu">
					@foreach($mr->projectTaskAttachent as $pta)
					<li>
						@if(getimagesize(url('/').'/task_attachments/'.$pta->attachment))
						<a target="_blank" href="#">
							<img src="{{ public_path().'/task_attachments/'.$pta->attachment }}" alt="{{ $mr->subject }}" style="width:150px;max-height: 210px;">
						</a>
						@else
							{{$pta->attachment}} FILE
						@endif
					</li>
					@endforeach

					</ul>
					@endif
		      </li>
		      @endforeach
		    </ol>
		    @endforeach
		 </ol>
    @endforeach
  </li>
</ol>


<table id='ledgend'>
	<thead>
		<tr>
			<th>Status</th>
			<th>Total</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>Completed</td>
			<td>{{$completed}}</td>
		</tr>
		<tr>
			<td>Pending</td>
			<td>{{$ongoing}}</td>
		</tr>
		<tr>
			<td>Schedule</td>
			<td>{{$schedule}}</td>
		</tr>
	</tbody>
</table>
</section>

<footer style="bottom: 0;float: right;position: absolute;color: black;">

<small>Generated By Meronetwork</small>
	
</footer>

</body>
</html>