@extends('layouts.master')

@section('head_extra')
    <!-- Select2 css -->
    @include('partials._head_extra_select2_css')

@endsection

@section('content')
<style>
    .box-comment { margin-bottom: 5px; padding-bottom: 5px; border-bottom: 1px solid #eee; }
    .box-comment img {float: left; margin-right:10px;}
    .username { font-weight: bold; }
    .comment-text span{display: block;}
</style>

    <div class='row'>
        <div class='col-md-12'>

            <section class="invoice">
      <!-- title row -->
      <div class="row">
        <div class="col-xs-12">
          <h2 class="page-header">
            <img style="max-width: 240px" height="" src="{{env('APP_URL')}}{{ '/org/'.$organization->logo }}">
            <span class="pull-right">
             
                <a href="/admin/location/stocktransfer">
            <button type="button" class="btn btn-xs btn-success pull-right">
              <i class="fa fa-times-circle"></i> Close
            </button>
          </a> &nbsp;
             
           <a href="/admin/location/stocktransfer/print/{{ $locationstocktransfer->id }}" target="_blank" class="btn btn-xs btn-default pull-right"><i class="fa fa-print"></i> Print</a>&nbsp;&nbsp;
             
          <a href="/admin/location/stocktransfer/pdf/{{ $locationstocktransfer->id }}">
            <button type="button" class="btn btn-xs btn-primary pull-right" style="margin-right: 5px;">
              <i class="fa fa-download"></i> PDF
            </button>
          </a> &nbsp; 


            </span>
          </h2>
        </div>
        <!-- /.col -->
      </div>
      <!-- info row -->
      <div class="row invoice-info">
        <div class="col-sm-4 invoice-col">

          <address>
            <span style="font-size: 16.5px">{{ env('APP_COMPANY') }} </span><br>
            {{ env('APP_ADDRESS1') }}<br>
            {{ env('APP_ADDRESS2') }}<br>
            Phone: {{ env('APP_PHONE1') }}<br>
            Email: {{ env('APP_EMAIL') }}<br/>
            Generated by: {{ $locationstocktransfer->user->first_name}} {{ $locationstocktransfer->user->last_name}}<br>
            Sellers PAN:  {{ \Auth::user()->organization->tpid }}
          </address>
        </div>
        <!-- /.col -->
        <div class="col-sm-4 invoice-col">
          To
          <address>
            <span style="font-size: 16.5px">{{ $locationstocktransfer->destination->location_name }}</span><br>
          </address>
          From
           <address>
            <span style="font-size: 16.5px">{{ $locationstocktransfer->source->location_name }}</span><br>
          </address>
        </div>
        <!-- /.col -->
        <div class="col-sm-4 invoice-col">

          <b>Transfer Date:</b> {{ date("d/M/Y", strtotime($locationstocktransfer->transfer_date )) }}<br>
         
          <b>Status:</b> {{ ucfirst($locationstocktransfer->status) }} <br>

        </div>
        <!-- /.col -->
      </div>

      <!-- Table row -->
      <div class="row">
        <div class="col-xs-12 table-responsive">
          <table id="" class="table table-striped">
            <thead class="bg-gray">
            <tr>
              <th>Description</th>
            
              <th>Qty</th>
              <th>Reason</th>
            </tr>
            </thead>
            <tbody>
                @foreach($locationstocktransferdetail as $odk => $odv)

                <tr>
                  <td>{{ $odv->product->name }}</td>
                 
                  <td>{{ $odv->quantity }}</td>
                  <td>{{ $odv->reason }}</td>
                 
                </tr>
                @endforeach
            </tbody>
          </table>
        </div>
        <!-- /.col -->
      </div>



      <div class="row">
        <!-- accepted payments column -->
        <div class="col-xs-6">


            <h4> Special Notes and Instruction</h4>
            <p class="text-muted well well-sm well-primary no-shadow" style="margin-top: 10px;">
           {!! nl2br($locationstocktransfer->comment) !!}
        </p>

          <p class="text-muted well well-sm well-success no-shadow" style="margin-top: 10px;">
                ___________________________________

                <br>Authorized Signature
          </p>
        </div>
       
      </div>
      <!-- /.row -->

      <!-- this row will not appear when printing -->
      <div class="row no-print">
        <div class="col-xs-12">
         

         
        </div>
      </div>
    </section>



        </div><!-- /.col -->

    </div><!-- /.row -->


   

@endsection

@section('body_bottom')
    <!-- Select2 js -->
    @include('partials._body_bottom_select2_js_user_search')
@endsection
