
    <div class='row' style="padding-left: 10px;margin-right: 3px;">
        <div class='col-md-12' id='printElement'>

          
      <!-- title row -->
      <div class="row">
        <div class="col-xs-12">
          <h2 class="page-header">
            <img width="240" src="{{env('APP_URL')}}/{{ '/org/'.$organization->logo }}">
            <span class="pull-right"  id='tools'>
           
                &nbsp;
                <a href="#">
            <button type="button" class="btn btn-xs btn-success pull-right"  data-dismiss="modal">
              <i class="fa fa-times-circle"></i> Close
            </button>
          </a> &nbsp;
              @if($ord->status != 'Invoiced')
                @if($ord->order_type == 'proforma_invoice')
                  <a class="btn btn-xs btn-primary pull-right" href="{!! route('admin.invoice.confirm-invoice', $ord->id) !!}" data-toggle="modal" data-target="#modal_dialog"> Post Invoice</a> &nbsp;
                @endif
              @endif
               <a href="/admin/credit_note/orders/print/{{$ord->id}}/print" target="_blank" class="btn btn-xs btn-default pull-right" ><i class="fa fa-print"></i> Print</a>&nbsp;&nbsp;
             

        
           &nbsp; 
        
            </span>
          </h2>
        </div>
        <!-- /.col -->
      </div>
      <!-- info row -->

        <div class="row invoice-info">

        <div class="col-sm-4 invoice-col">
    <h2 style="margin-top: -10px;">Credit Note</h2>
          <address>
            <span style="font-size: 16.5px">{{ env('APP_COMPANY') }} </span><br>
            {{ env('APP_ADDRESS1') }}<br>
            {{ env('APP_ADDRESS2') }}<br>
            Phone: {{ env('APP_PHONE1') }}<br>
            Email: {{ env('APP_EMAIL') }}<br/>
            Generated by: {{ $ord->user->first_name}} {{ $ord->user->last_name}}<br>
            Sellers PAN:  {{ \Auth::user()->organization->vat_id }}
          </address>
        </div>
        <!-- /.col -->
        <div class="col-sm-4 invoice-col">
          To
          <address>
            <span style="font-size: 16.5px">{{ $ord->name }}</span><br>
            Email: @if($ord->source == 'lead')<a href="mailto:{{ $ord->lead->email }}">{{ $ord->lead->email }}</a>@else<a href="mailto:{{ $ord->client->email }}">{{ $ord->client->email }}</a>@endif<br>
            @if($ord->source=='client') {{ $ord->client->name }} @else {{ $ord->lead->name }} @endif
            <br/>
           Address: {!! nl2br($ord->address ) !!}<br/>
           @if($ord->source == 'client') Purchaser's PAN: {!! $ord->customer_pan  !!} @endif

          </address>
        </div>
        <!-- /.col -->
        <div class="col-sm-4 invoice-col">
          <b>Credit Note Number: #CN{{ $returnnote->credit_note_no??'-' }}</b><br>
          <b>Bill No:</b><span style="font-weight:bold">{{$ord->bill_no??'-'}}</span><br>
          <b>Bill Date:</b> {{ date("d/M/Y", strtotime($ord->bill_date )) }}<br>
          <?php $timestamp = strtotime($ord->created_at) ?>
          <b>Valid Till:</b> {{ date("d/M/Y", strtotime("+30 days", $timestamp )) }}<br>
          <b>Terms :</b> {!! $ord->terms  !!}<br>
          <b>{{ ucwords($ord->source) }} Account:</b> #@if($ord->source == 'lead') {{ $ord->lead->id }} @else {{ $ord->client->id }} @endif<br>
          <b>Source:</b> {{ ucfirst($ord->source) }} 
        </div>
        <!-- /.col -->
      </div>

      <!-- /.row -->
      <p>Your Credit Note issued for: <Span style="color:red;font-weight:bold">{{$returnnote->void_reason}}</Span></p>
      <!-- Table row -->
      <div class="row">
        <div class="col-xs-12 table-responsive">
          <table id="" class="table table-striped">
            <thead class="bg-gray">
            <tr>
              <th>Description</th>
              <th>Price</th>
              <th>Qty</th>
              <th>Total</th>
            </tr>
            </thead>
            <tbody>
                @foreach($orderDetails as $odk => $odv)

                <tr>
                  @if($odv->is_inventory == 1)
                  <td>{{ $odv->product->name }}</td>
                  @elseif($odv->is_inventory == 0)
                  <td>{{ $odv->description }}</td>
                  @endif
                  <td>{{ $odv->price }}</td>
                  <td>{{ $odv->quantity }}</td>
                  <td>{{ env('APP_CURRENCY').' '.$odv->total }}</td>
                </tr>
                @endforeach
            </tbody>
          </table>
        </div>
        <!-- /.col -->
      </div>



      <div class="row">
        <!-- accepted payments column -->
        <div class="col-xs-6">
          <?php
           $f = new \NumberFormatter("en", \NumberFormatter::SPELLOUT);
           ?>

          <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;text-transform: capitalize;font-size: 16.5px">
            In Words: {{ $f->format($ord->total_amount)}}
            </p>


          <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
            Above information is only an estimate of services/goods described above.
            </p>

            <h4> Special Notes and Instruction</h4>
            <p class="text-muted well well-sm well-primary no-shadow" style="margin-top: 10px;">
           {!! nl2br($ord->comment) !!}
        </p>

          <p class="text-muted well well-sm well-success no-shadow" style="margin-top: 10px;">
                ___________________________________

                <br>Authorized Signature
          </p>
        </div>
        <!-- /.col -->
        <div class="col-xs-6">


          <div class="table-responsive">
            <table id="" class="table table-striped">
              <tbody>
                <tr style="padding:0px; margin:0px;">
                <th style="width:50%" >Sub Total:</th> <td>{{ env('APP_CURRENCY').' '. number_format($ord->subtotal,2) }}</td>
              </tr>
               <tr style="padding:0px; margin:0px;">
                <th style="width:50%">Discount Percentage(%)</th> <td>{{$ord->discount_percent }}%</td>
              </tr>
              <tr>
                <th style="width:50%">Taxable Amount</th> <td>{{env('APP_CURRENCY').' '. number_format($ord->taxable_amount,2) }}</td>
              </tr>
              <tr style="padding:0px; margin:0px;">
                <th style="width:50%">Tax Amount(13%):</th> <td>{{ env('APP_CURRENCY').' '. number_format($ord->tax_amount,2) }}</td>
              </tr>
               <tr style="padding:0px; margin:0px;">
                <th style="width:50%">Total:</th> <td style="font-size: 16.5px">{{ env('APP_CURRENCY').' '. number_format($ord->total_amount,2) }}</td>
              </tr>
            <!--   <tr>
                <th>Discount:</th>
                <td>{{ env('APP_CURRENCY').' '.($ord->discount_amount ? $ord->discount_amount : '0') }}</td>
              </tr>
              <tr>
                <th>Tax Amount</th>
                <td>{{ env('APP_CURRENCY').' '.$ord->total_tax_amount }}</td>
              </tr>

              <tr>
                <th>Total:</th>
                <td>{{ env('APP_CURRENCY').' '.$ord->total }}</td>
              </tr> -->
            </tbody></table>
          </div>
        </div>
        <!-- /.col -->
      </div>



      <div class="row" style="margin-top: 100px;padding-left: 5px;">
        <div class="col-md-12">
            <div align="center">Thank You for your custom</div>
        <p  style="border-top-style: dashed;margin-top: 30px;"></p>
              <div class="row invoice-info">

        <div class="col-sm-4 invoice-col">
    <h2 style="margin-top: -10px;">Credit Advice</h2>
          <address>
            <span style="font-size: 16.5px">{{ env('APP_COMPANY') }} </span><br>
            {{ env('APP_ADDRESS1') }}<br>
            {{ env('APP_ADDRESS2') }}<br>
            Phone: {{ env('APP_PHONE1') }}<br>
            Email: {{ env('APP_EMAIL') }}<br/>
            Generated by: {{ $ord->user->first_name}} {{ $ord->user->last_name}}<br>
            Sellers PAN:  {{ \Auth::user()->organization->vat_id }}
          </address>
        </div>
        <!-- /.col -->
        <div class="col-sm-4 invoice-col">
          To
          <address>
            <span style="font-size: 16.5px">{{ $ord->name }}</span><br>
            Email: @if($ord->source == 'lead')<a href="mailto:{{ $ord->lead->email }}">{{ $ord->lead->email }}</a>@else<a href="mailto:{{ $ord->client->email }}">{{ $ord->client->email }}</a>@endif<br>
            @if($ord->source=='client') {{ $ord->client->name }} @else {{ $ord->lead->name }} @endif
            <br/>
           Address: {!! nl2br($ord->address ) !!}<br/>
           @if($ord->source == 'client') Purchaser's PAN: {!! $ord->customer_pan  !!} @endif

          </address>
        </div>
        <!-- /.col -->
        <div class="col-sm-4 invoice-col">
          <b>Credit Note Number: #CN{{ $ord->credit_note_no }}</b><br>


          <b>Bill Date:</b> {{ date("d/M/Y", strtotime($ord->bill_date )) }}<br>
          <?php $timestamp = strtotime($ord->created_at) ?>
          <b>Valid Till:</b> {{ date("d/M/Y", strtotime("+30 days", $timestamp )) }}<br>
          <b>Terms :</b> {!! $ord->terms  !!}<br>
          <b>{{ ucwords($ord->source) }} Account:</b> #@if($ord->source == 'lead') {{ $ord->lead->id }} @else {{ $ord->client->id }} @endif<br>
          <b>Source:</b> {{ ucfirst($ord->source) }} 
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
      <p><b>Please Deduct this credit from your next payment to us</b></p>
      <div class="row">
        <div class="col-md-8">
          {{ env('APP_COMPANY') }}, {{ env('APP_ADDRESS1') }},{{ env('APP_PHONE1') }}
        </div>
        <div class="col-md-4">
          {{ env('APP_EMAIL') }}
        </div>
      </div>
      <br> 
      <!-- /.row -->

      <!-- this row will not appear when printing -->
      <div class="row no-print">
        <div class="col-xs-12">
         

         
        </div>
      </div>
    


        </div>
      


        </div><!-- /.col -->



   


    </div><!-- /.row -->

</div>
       <!--Modal start-->

  <!--Modal end -->
<script type="text/javascript">
function print() {
$('#tools').hide();
  printJS({
      printable: 'printElement',
      type: 'html',
      style: 'img{width: 20px;}',
      targetStyles: ['*']
  });
 $('#tools').show();
}

$('#printButton').click(function(){
   
   print();
});

</script>