<!DOCTYPE html>
<html lang="en"><head>
    <meta charset="utf-8">
    <title>{{ env('APP_COMPANY')}} | Purchase Order</title>
    <style type="text/css">

@font-face {
  font-family: SourceSansPro;
  src: url(SourceSansPro-Regular.ttf);
}

.clearfix:after {
  content: "";
  display: table;
  clear: both;
}
a {
  color: #0087C3;
  text-decoration: none;
}
body {
  position: relative;
  width: 18cm;
  height: 24.7cm;
  margin: 0 auto;
  color: #555555;
  background: #FFFFFF;
  font-family: Arial, sans-serif;
  font-size: 12px;
}
header {
  padding: 10px 0;
  margin-bottom: 20px;
  border-bottom: 1px solid #AAAAAA;
}

table {
  width: 100%;
  border-collapse: collapse;
  border-spacing: 0;
  margin-bottom: 5px;
}

table th,
table td {
  padding: 3px;
  background:;
  text-align: left;
  border-bottom: 1px solid #FFFFFF;
}

table th {
  white-space: nowrap;
  font-weight: normal;
}

table td {
  text-align: left;
}

table td h3{
  color: #57B223;
  font-size: 1.2em;
  font-weight: normal;
  margin: 0 0 0.2em 0;
}

table .no {
  color: #FFFFFF;
  font-size: 1em;
  background: #57B223;
}

table .desc {
  text-align: left;
}

table .unit {
  background: #DDDDDD;
}

table .qty {
}

table .total {
  background: #57B223;
  color: #FFFFFF;
}

table td.unit,
table td.qty,
table td.total {
  font-size: 1.2em;
}

table tbody tr:last-child td {
  border: none;
}

table tfoot td {
  padding: 5px 10px;
  background: #FFFFFF;
  border-bottom: none;
  font-size: 1em;
  white-space: nowrap;
  border-top: 1px solid #AAAAAA;
}

table tfoot tr:first-child td {
  border-top: none;
}

table tfoot tr:last-child td {
  color: #57B223;
  font-size: 1em;
  border-top: 1px solid #57B223;
  font-weight: bold;

}

table tfoot tr td:first-child {
  border: none;
}

#thanks{
  font-size: 2em;
  margin-bottom: 50px;
}

#notices{
  padding-left: 6px;
  border-left: 6px solid #0087C3;
}

#notices .notice {
  font-size: 1.2em;
}

footer {
  color: #777777;
  width: 100%;
  height: 30px;
  position: absolute;
  bottom: 0;
  border-top: 1px solid #AAAAAA;
  padding: 8px 0;
  text-align: center;
}
    </style>

  </head><body>
    <header class="clearfix">

     <table>
            <tr>
        <td width="50%" style="float:left">
          <div id="logo">
            <img style="max-width: 150px" src="{{public_path()}}/{{ '/org/shree.jpeg' }}">
          </div>
        </td>
        <td width="50%" style="text-align: right">
        <div  id="company">
          <h4 class="name">{{ env('APP_COMPANY') }} </h4>
          <div>{{ env('APP_ADDRESS1') }}</div>
          <div>PAN: {{ env('TPID') }}</div>
          <div><a href="mailto:{{ env('APP_EMAIL') }}">{{ env('APP_EMAIL') }}</a></div>
        </div>
        </td></tr>

      </table>

      </div>
    </header>
    <main>


      <div id="details" class="clearfix">

        <table>
          <TR><TD>
        <div id="client" width="50%" style="float:left">
          <div class="to">{{ ucwords(str_replace("_", " ", ucfirst($ord->purchase_type)))}}</div>

          <h2 class="name">{{ $ord->client->name }}</h2>
          <div class="address">Phone: {!! $ord->client->phone !!}<br/></div>
          <div class="address">Address: {!! nl2br($ord->client->location ) !!}<br/></div>
           <div class="address">Email: {!! nl2br($ord->client->email ) !!}<br/></div>
            <div class="address">PAN NO: {!! nl2br($ord->pan_no ) !!}<br/></div>
        </div>
      </TD><TD  width="50%" style="text-align: right">

        <div id="invoice">
          <h3>{{ ucwords(str_replace("_", " ", ucfirst($ord->purchase_type)))}} {{env('APP_CODE')}} {{ $ord->reference }}</h3>
          <h3>Bill No. {{ $ord->bill_no }} </h3>
          <div class="date">Date of {{ ucwords(str_replace("_", " ", ucfirst($ord->purchase_type)))}}: {{ date("d/M/Y", strtotime($ord->bill_date )) }}</div>
          <div class="date">Delivery Date: {{ date("d/M/Y", strtotime($ord->delivery_date )) }}</div>
          <div>Vendor Reg No:</b> #{{ $ord->supplier_id }}</div>
          <div>Generated by: {{ $ord->user->first_name}} {{ $ord->user->last_name}}</div>
        </div>
      </div>
    </TD></TR>

    </table>

    <!-- /.row --><br><br>
      <p>Your negotiations and agreement to do business are conditioned on your acceptence of and compliance with these terms.
      The {{ ucwords(str_replace("_", " ", ucfirst($ord->purchase_type)))}} is requested by the {{ env('APP_COMPANY') }}.</p>


      <table border="0" cellspacing="0" cellpadding="0">
        <thead>
          <tr>
            <th class="no">#</th>
            <th class="no">PRODUCT</th>
            <th class="no">PRICE</th>
            <th class="no">QUANTITY</th>
            <th class="no">TOTAL</th>
          </tr>
        </thead>
        <tbody>
          <?php
          $n= 0;
          $perunitexciseamt=\DB::table('importpurchase')->join('purch_order_details','importpurchase.purchase_order_id', '=', 'purch_order_details.order_no',)->where('cost_type',"EXCISE DUTY")->Where('purchase_order_id', $ord->id)->select('importpurchase.amount','purch_order_details.qty_invoiced')->get()->toArray();
          foreach($perunitexciseamt as $exciseamt){
           
            $totalexcise=$totalexcise+($exciseamt->qty_invoiced*(double)$exciseamt->amount);
        
          }
          ?>
          @foreach($orderDetails as $odk => $odv)
          
          <tr>
            <td>{{++$n}}</td>
             @if($odv->is_inventory == 1)
             <td>{{ $odv->product->name }}</td>
             @elseif($odv->is_inventory == 0)
            <td>{{ $odv->description }}</td>
            @endif
            <td>{{$ord->currency.' '.number_format($odv->unit_price,2) }}</td>
            <td>{{ $odv->qty_invoiced }}</td>

            <td>{{ $ord->currency.' '.number_format($odv->total,2) }}</td>
            @if($ord->is_import==1)
            @endif
          </tr>
         @endforeach

        </tbody>
        <tfoot>
          <tr>
            <td colspan="2"></td>
            <td colspan="2">SubTotal</td>
            <td>{{ $ord->currency.' '. number_format($ord->subtotal,2) }}</td>
          </tr>
          <tr>
            <td colspan="2"></td>
            <td colspan="2">Total Excise Amount</td>
            <td>{{$ord->currency.' '. number_format($totalexcise,2) }}</td>
          </tr>
          <tr>
            <td colspan="2"></td>
            <td colspan="2">Taxable Amount</td>
            <td>{{$ord->currency.' '. number_format($ord->subtotal+$totalexcise,2) }}</td>
          </tr>
          <tr>
            <td colspan="2"></td>
            <td colspan="2">Discount Amount</td>
            <td>{{$ord->currency.' '. number_format($ord->discount_amount,2) }}</td>
          </tr>
         
          
           <tr>
            <td colspan="2"></td>
            <td colspan="2">Tax Amount </td>
            <td>{{ $ord->currency.' '. number_format(($ord->subtotal+$totalexcise)*0.13,2) }}</td>
          </tr>
          <tr>
            <td colspan="2"></td>
            <td colspan="2">Total</td>
            <td>{{ $ord->currency.' '. number_format(($ord->subtotal+$totalexcise)+(($ord->subtotal+$totalexcise)*0.13),2) }}</td>
          </tr>
        </tfoot>
      </table>
      <div id="">
        <?php

        $f = new \NumberFormatter("en", \NumberFormatter::SPELLOUT);
      ?>
     In Words:<?php $f->format($ord->total) ?></div>
     <br>
     <div id="notices">
       <div>NOTICE:</div>
       <div class="notice">{!! nl2br($ord->comments) !!}</div>
     </div>
      @if($ord->is_import==1)
        <p>Additional Cost</p>
        <div class="col-xs-12 table-responsive">
            <table border="0" cellspacing="0" cellpadding="0">
                <thead >
                    <tr>
                        <th class="no">#</th>
                        <th class="no">Cost Type</th>
                        <th class="no">Product</th>
                        <th class="no">Method</th>
                        <th class="no">Amount</th>
                        <th class="no"> Debit Amount </th>
                        <th class="no">Credit Amount</th>
                        <th class="no">Description</th>
                    </tr>
                </thead>
                <tbody>
                    @php
                        $importpurchase=\App\Models\ImportPurchase::where('purchase_order_id',$ord->id)->get();
                    @endphp
                    @foreach($importpurchase as $item)
                    <tr>
                        <td>{{$loop->index+1}}</td>
                        <td>{{$item->cost_type}}</td>
                        <td>{{ $item->product_id==0?'All Product':\App\Models\Product::find($item->product_id)->name }}</td>
                        <td>{{ $item->method }}</td>
                        <td>{{ number_format($item->amount,2) }}</td>
                        <td>{{ \App\Models\COALedgers::find($item->debit_account_ledger_id)->name }}</td>
                        <td>{{ \App\Models\COALedgers::find($item->credit_account_ledger_id)->name}}</td>
                        <td>{{ $item->description}}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
      @endif
      <div id=""> ___________________________________</div>
      <div id="">Authorized Signature</div>


    </main>
    <footer>
      {{ ucwords(str_replace("_", " ", ucfirst($ord->purchase_type)))}} was created on MEROCRM.
    </footer>
  </body></html>
