<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
  <head>
    <meta charset="UTF-8">
    <title>{{ env('APP_COMPANY')}} | PROPOSAL</title>

    <!-- block from searh engines -->
    <meta name="robots" content="noindex">
    <!-- Tell the browser to be responsive to screen width -->
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Set a meta reference to the CSRF token for use in AJAX request -->
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <!-- Bootstrap 3.3.4 -->
    <link href="{{ asset("/bower_components/admin-lte/bootstrap/css/bootstrap.min.css") }}" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons 4.7.0 -->
    <link href="{{ asset("/bower_components/admin-lte/font-awesome/css/all.css") }}" rel="stylesheet" type="text/css" />
    <!-- Ionicons 2.0.1 -->
    <link href="{{ asset("/bower_components/admin-lte/ionicons/css/ionicons.min.css") }}" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="{{ asset("/bower_components/admin-lte/dist/css/AdminLTE.min.css") }}" rel="stylesheet" type="text/css" />

    <!-- Application CSS-->
    <link href="{{ asset(elixir('css/all.css')) }}" rel="stylesheet" type="text/css" />


  </head>

<body onload="window.print();" cz-shortcut-listen="true" class="skin-blue sidebar-mini">

  <div class='wrapper'>
  	
      <section class="invoice">
        <!-- title row -->
        <div class="row">
          <div class="col-xs-12">
            <h2 class="page-header">
              <img width="" src="{{env('APP_URL')}}/{{ '/org/'.$organization->logo }}">
              <span class="pull-right">
                <span>{{ ucwords($hrletter->type) }}</span>
              </span>
            </h2>
          </div>
          <!-- /.col -->
        </div>

        <div class="row invoice-info">
          <div class="col-sm-4 invoice-col">
            <address>
              <strong>{{ env('APP_COMPANY') }} </strong><br>
              Status: {{ ucfirst($hrletter->status)}}<br/>
              Generatted on: {{ $hrletter->created_at}}<br/>
              Reference #: {{env('APP_CODE')}} {{date(y)}}-0{{ $hrletter->id}}<br/>
              <!-- Generated by: {{ $hrletter->user->first_name}} {{ $hrletter->user->last_name}} -->
            </address>
          </div>
          <!-- /.col -->
          <div class="col-sm-4 invoice-col">
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
        <hr/>
        {!! $hrletter->body !!}
        <hr/>

      </section>

  </div><!-- /.col -->

</body>
