@extends('layouts.master')

@section('head_extra')
    <!-- Select2 css -->
    @include('partials._head_extra_select2_css')

@endsection

@section('content')
    <div class='row'>
        <div class='col-md-12'>
          
            <section class="invoice">
      <!-- title row -->
      <div class="row">
        <div class="col-xs-12">
          <h2 class="page-header">
            <img width="" src="{{env('APP_URL')}}/{{ '/org/'.$organization->logo }}">
            <span class="pull-right">
              <span>{{ ucfirst($hrletter->type) }}</span>
            </span>
          </h2>
        </div>
        <!-- /.col -->
      </div>
      <!-- info row -->
      <div class="row invoice-info">
        <div class="col-sm-4 invoice-col">
          <address>
            <strong>{{ env('APP_COMPANY') }} </strong><br>
            Status: {{ ucfirst($hrletter->status)}}<br/>
            Generatted on: {{ $hrletter->created_at}}<br/>
            Reference #: {{env('APP_CODE')}} {{date(y)}}-0{{ $hrletter->id}}<br/>
            <!-- Generated by: {{ $hrletter->user->first_name}} {{ $hrletter->user->last_name}} -->
          </address>
        </div>
        <!-- /.col -->
        <div class="col-sm-4 invoice-col">
          <b>
            @if($hrletter->staff_id == 0)
             No Staff
             @else
             Name: {{ $hrletter->user->first_name }} {{ $hrletter->user->last_name }}
             @endif
          </b><br>
          
          Type: {{ $hrletter->type}}<br/>
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
      <hr/>
      {!! $hrletter->body !!}
      <hr/>

      
      <!-- /.row -->

      <!-- this row will not appear when printing -->
      <div class="row no-print">
        <div class="col-xs-12">
          <a href="/admin/hrletter/print/{{ $hrletter->id }}" target="_blank" class="btn btn-default"><i class="fa fa-print"></i> Print</a>

          <a href="/admin/hrletter/{!! $hrletter->id !!}/show-mailmodal" class="btn btn-default" data-toggle="modal" data-target="#modal_mail">  <i class="fa fa-envelope"></i> Send Email</a>

          <a href="/admin/hrletter">
            <button type="button" class="btn btn-success pull-right">
              <i class="fa fa-times-circle"></i> Close 
            </button>
          </a>
          <a href="/admin/hrletter/{{$hrletter->id}}/edit">
            <button type="button" class="btn btn-success pull-right">
              <i class="fa fa-times-circle"></i> Edit 
            </button>
          </a>
          <a href="/admin/hrletter/generatePDF/{{ $hrletter->id }}">
            <button type="button" class="btn btn-primary pull-right" style="margin-right: 5px;">
              <i class="fa fa-download"></i> Generate PDF
            </button>
          </a>
        </div>
      </div>
    </section>



        </div><!-- /.col -->

    </div><!-- /.row -->

@endsection

@section('body_bottom')
    <!-- Select2 js -->
    @include('partials._body_bottom_select2_js_user_search')
@endsection
