@extends('layouts.master')

@section('head_extra')
    <!-- Select2 css -->
    @include('partials._head_extra_select2_css')

@endsection
<section class="content-header" style="margin-top: -35px; margin-bottom: 20px">
            <h1>
                {{ $page_title ?? "Page Title"}} 
                <small> {{ $page_description ?? "Page Description" }}</small>
            </h1>
            {!! MenuBuilder::renderBreadcrumbTrail(null, 'root', false)  !!}
</section>
@section('content')
    <div class='row'>
        <div class='col-md-12'>
          
            <section class="invoice">
      <!-- title row -->
      <div class="row">
        <div class="col-xs-12">
          <h2 class="page-header">
            <img width="" src="{{env('APP_URL')}}/{{ '/org/'.$organization->logo }}">
            <span class="pull-right">
              <span>{{ ucfirst($proposal->type) }}</span>
            </span>
          </h2>
        </div>
        <!-- /.col -->
      </div>
      <!-- info row -->
      <div class="row invoice-info">
        <div class="col-sm-4 invoice-col">
          <address>
            <strong>{{ env('APP_COMPANY') }} </strong><br>
            Status: {{ ucfirst($proposal->status)}}<br/>
            Generatted on: {{ $proposal->created_at}}<br/>
            Reference #: {{date(y)}}-0{{ $proposal->id}}<br/>
            <!-- Generated by: {{ $proposal->user->first_name}} {{ $proposal->user->last_name}} -->
          </address>
        </div>
        <!-- /.col -->
        <div class="col-sm-4 invoice-col">
          <b>
             <a href="/admin/leads/{{$proposal->client_lead_id}}">{{ $proposal->lead->name }}</a> 
          </b><br>
          
          Product: {{ $proposal->product->name}}<br/>
          Type: {{ $proposal->type}}<br/>
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
      <hr/>
      {!! $proposal->body !!}
      <hr/>

      
      <!-- /.row -->

      <!-- this row will not appear when printing -->
      <div class="row no-print">
        <div class="col-xs-12">
          <a href="/admin/proposal/print/{{ $proposal->id }}" target="_blank" class="btn btn-default"><i class="fa fa-print"></i> Print</a>

          <a href="/admin/proposalMail/{!! $proposal->id !!}/show-mailmodal" class="btn btn-default" data-toggle="modal" data-target="#modal_mail">  <i class="fa fa-envelope"></i> Send Email</a>

          <a href="/admin/proposal">
            <button type="button" class="btn btn-success pull-right">
              <i class="fa fa-times-circle"></i> Close 
            </button>
          </a>

          <a href="/admin/proposal/{{$proposal->id}}/edit">
            <button type="button" class="btn btn-success pull-right">
              <i class="fa fa-times-circle"></i> Edit 
            </button>

          <a href="/admin/proposal/generatePDF/{{ $proposal->id }}">
            <button type="button" class="btn btn-primary pull-right" style="margin-right: 5px;">
              <i class="fa fa-download"></i> Generate PDF
            </button>
          </a>
        </div>
      </div>
    </section>



        </div><!-- /.col -->

    </div><!-- /.row -->

@endsection

@section('body_bottom')
    <!-- Select2 js -->
    @include('partials._body_bottom_select2_js_user_search')
@endsection
