@extends('layouts.master')

@section('head_extra')
    <!-- Select2 css -->
    @include('partials._head_extra_select2_css')

@endsection

@section('content')
<style>
    .box-comment { margin-bottom: 5px; padding-bottom: 5px; border-bottom: 1px solid #eee; }
    .box-comment img {float: left; margin-right:10px;}
    .username { font-weight: bold; }
    .comment-text span{display: block;}
</style>
    <div class='row'>
        <div class='col-md-12'>

            <section class="invoice">
      <!-- title row -->
      <div class="row">
        <div class="col-xs-12">
          <h2 class="page-header">
            <img width="200px" src="{{ env('APP_LOGO_INVOICE') }}">
            <span class="pull-right">
              <span>{{ ucwords(str_replace("_", " ", ucfirst($ord->order_type)))}}</span>
            </span>
            <a href="/admin/order/list">
              <button type="button" class="btn btn-success pull-right" style="margin-right: 5px;">
                <i class="fa fa-times-circle"></i> Close
              </button>
            </a>
            <!-- <a href="/admin/payment/create/{{$orderNo.'/'.$invoiceNo}}"  class="btn btn-warning pull-right" style="margin-right: 5px;"><i class="fa fa-money-bill-alt"></i>Pay Now</a> -->

            <a href="#"  class="btn btn-warning pull-right" style="margin-right: 5px;">Convert to invoice</a>

            <a href="/admin/quotation/print/{{ $saleDataOrder->order_no }}" target="_blank" class="btn btn-default pull-right" style="margin-right: 5px;"><i class="fa fa-print"></i>Print</a>

            <a href="/admin/mail/quotation/{!! $saleDataOrder->order_no !!}/show-mailmodal" class="btn btn-default pull-right"   style="margin-right: 5px;">  <i class="fa fa-envelope"></i> Send Email</a>

            <a href="/admin/quotation/generatePDF/{{  $saleDataOrder->order_no }}">
              <button type="button" class="btn btn-primary pull-right" style="margin-right: 5px;">
                <i class="fa fa-download"></i> Generate PDF
              </button>
            </a>
          </h2>
        </div>
        <!-- /.col -->
      </div>
      <!-- info row -->
      <div class="row invoice-info">
        <div class="col-sm-4 invoice-col">
          <address>
            <strong>{{ env('APP_COMPANY') }} </strong><br>
            {{ env('APP_ADDRESS1') }}<br>
            {{ env('APP_ADDRESS2') }}<br>
            Phone: {{ env('APP_PHONE1') }}<br>
            Email: {{ env('APP_EMAIL') }}<br/>
            Generated by: {{ $saleDataOrder->user->first_name}} {{ $ord->user->last_name}}
          </address>
        </div>
        <!-- /.col -->
        <div class="col-sm-4 invoice-col">
          To
          <address>
            <strong>{{ $saleDataOrder->lead->name }}</strong><br>
            {{ $saleDataOrder->lead->mob_phone  }}<br/>
            {!! $saleDataOrder->lead->email  !!}
          </address>
        </div>
        <!-- /.col -->
        <div class="col-sm-4 invoice-col">
          <b>{{ ucwords(str_replace("_", " ", ucfirst($saleDataOrder->order_type)))}} #{{ $ord->id }}</b><br>


          <b>Issue Date:</b> {{ date("d/M/Y", strtotime($saleDataOrder->created_at )) }}<br>
          <?php $timestamp = strtotime($saleDataOrder->created_at) ?>
          <b>Valid Till:</b> {{ date("d/M/Y", strtotime("+30 days", $timestamp )) }}<br>
          <b>Terms :</b> Nett 15<br>
          <b>Customer Account:</b> #{{ $ord->client_id }}
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
      Thank you for choosing {{ env('APP_COMPANY') }}. Your Quotation is detailed below. If you find errors or desire certain changes, please contact us.
<hr/>
      <!-- Table row -->
      <div class="row">
        <div class="col-xs-12 table-responsive">
          <table class="table table-striped">
            <thead>
            <tr>
              <th>Product ID</th>
              <th>Product</th>
              <th>Price</th>
              <th>Qty</th>
              <th>Tax(%) *</th>
              <th>Tax({{ env('APP_CURRENCY') }})</th>
              <th>Subtotal</th>
            </tr>
            </thead>
            <tbody>
                @foreach($salesDetails as $odk => $odv)
                <tr>
                  <td>#{{ $odv->id }}</td>
                  <td>{{ $odv->description }}</td>
                  <td>{{ $odv->unit_price }}</td>
                  <td>{{ $odv->quantity }}</td>
                  <td>{{ $odv->tax ? $odv->tax : 0 }}</td>
                  <td>{{ number_format($odv->tax_amount,2) }}</td>
                  <td>{{ env('APP_CURRENCY').' '.number_format($odv->unit_price, 2)}}</td>
                </tr>
                @endforeach
            </tbody>
          </table>
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

      <div class="row">
        <!-- accepted payments column -->
        <div class="col-xs-6">


          <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
            Above information is only an estimate of services/goods described above.
            </p>

            <h4> Special Notes and Instruction</h4>
            <p class="text-muted well well-sm well-primary no-shadow" style="margin-top: 10px;">
           {!! nl2br($saleDataOrder->comments) !!}
        </p>

          <p class="text-muted well well-sm well-success no-shadow" style="margin-top: 10px;">
            This {{ ucwords(str_replace("_", " ", ucfirst($ord->order_type)))}} includes VAT<br/>
              TPID: {{ \Auth::user()->organization->tpid }}
          </p>
        </div>
        <!-- /.col -->
        <div class="col-xs-6">


          <div class="table-responsive">
            <table class="table">
              <tbody><tr>
                <th style="width:50%">Total:</th>
                <td>{{ env('APP_CURRENCY').' '.number_format($saleDataOrder->total,2) }}</td>
              </tr>
            <!--   <tr>
                <th>Discount:</th>
                <td>{{ env('APP_CURRENCY').' '.($ord->discount_amount ? $ord->discount_amount : '0') }}</td>
              </tr>
              <tr>
                <th>Tax Amount</th>
                <td>{{ env('APP_CURRENCY').' '.$ord->total_tax_amount }}</td>
              </tr>

              <tr>
                <th>Total:</th>
                <td>{{ env('APP_CURRENCY').' '.$ord->total }}</td>
              </tr> -->
            </tbody></table>
          </div>
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

      <!-- this row will not appear when printing -->
      <!-- <div class="row no-print">
        <div class="col-xs-12">
          <a href="/admin/order/print/{{ $ord->id }}" target="_blank" class="btn btn-default"><i class="fa fa-print"></i>Print</a>

          <a href="/admin/payment/create/{{$orderNo.'/'.$invoiceNo}}"  class="btn btn-default"><i class="fa fa-print"></i>Pay Now</a>

          <a href="/admin/orders">
            <button type="button" class="btn btn-success pull-right">
              <i class="fa fa-times-circle"></i> Close
            </button>
          </a>

          <a href="/admin/order/generatePDF/{{ $ord->id }}">
            <button type="button" class="btn btn-primary pull-right" style="margin-right: 5px;">
              <i class="fa fa-download"></i> Generate PDF
            </button>
          </a>
        </div>
      </div> -->
    </section>



        </div><!-- /.col -->

    </div><!-- /.row -->




@endsection

@section('body_bottom')
    <!-- Select2 js -->
    @include('partials._body_bottom_select2_js_user_search')
@endsection
